service: kamal-test
image: friendlyantz/kamal-test
servers:
  - 192.168.1.46
registry:
  username: friendlyantz
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
traefik:
  options:
    publish:
      - "443:443"
  labels:
    traefik.http.routers.catchall.entryPoints: http
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"